# .github/workflows/update-auctions.yml

name: Update Auction House Data

on:
  # This makes it run every hour, on the hour
  schedule:
    - cron: "0 * * * *"
  # This also adds a button in the GitHub Actions tab to run it manually
  workflow_dispatch:

jobs:
  update_auctions:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Auction Update
        # This command makes a secure request to your API route
        run: |
          curl --request GET \
          --url '${{ secrets.PRODUCTION_URL }}/api/cron/update-auctions' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
